### ISSUE TITLE
incorrect base64 detection

### ISSUE THREAD

**Issue by kakaroto** [jsavko/debug-report#2]
Hi! This looks like a great module, someone just showed it to me! 👍 
One thing we noticed though is that it's detecting base64 data incorrectly, as it looks for occurences of 'base64' in the json string, however, on the Forge, we automatically detect base64 data during a entity update and instead move that data into an actual file on the assets library (S3) and replace the base64 data with a link to the file. The url is of the format `https://assets.forge-vtt.com/$userid/base64data/${hash}.${ext}`
Because of the occurences check of 'base64', it causes those urls to be incorrectly detected. 

I'd recommend changing it to a regexp like `/data:[a-zA-z0-9\/]*;base64,/` would work better, or just `;base64,` as a string.

**Comment by jsavko** [comment]
That’s a great suggestion and I hadn’t considered someone using base64 in the path.  I’ll push an update tonight with this change

**Comment by kakaroto** [comment]
Awesome, thanks for the quick response! :)
