### ISSUE TITLE
loadImage in code does not support external images

### ISSUE THREAD

**Issue by shemetz** [jsavko/debug-report#6]
I just tried the new version and had this bug occur (an error is thrown).

This part in code is the issue:

```
    let imgdata = await DebugDetails.loadImage('/' + game.scenes.active.background.src)
```

it fails if the scene background is, for example, this:  https://i.imgur.com/KylF5HH.jpg

Here is code that works for me (not sure if will work always):

```
    const imgSrc = game.scenes.active.background.src
    const imgUrl = imgSrc.startsWith('http') ? imgSrc : `/${imgSrc}`
    let imgdata = await DebugDetails.loadImage(imgUrl)
```

**Comment by jsavko** [comment]
Good catch. I hadn't considered remote images
